Greeting page was created.
wolox-training/enr-java pull request #1
Opened 2022-02-17 18:24 UTC by eliasrvt

## Summary

- A simple controller to say Hello was created.

## Trello Card

https://trello.com/c/fyFO8029

2022-02-21 13:45 UTC, sebas97-stack approved these changes

2022-02-21 13:46 UTC, sebas97-stack approved these changes

2022-02-23 13:59 UTC, sebas97-stack approved these changes, later dismissed

2022-02-24 14:01 UTC, sebas97-stack submitted a review, later dismissed

2022-02-24 17:23 UTC, juandbc requested changes

2022-02-24 17:23 UTC, juandbc commented on src/main/java/Wolox/training/models/Book.java
> +    @GeneratedValue(strategy = GenerationType.AUTO)
When we use PostgreSQL, the best strategy is **sequence**, so Hibernate can use a sequence table optimized by PostgreSQL. It is like declaring the column as **SERIAL** in the DDL script.
```suggestion
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
```

2022-02-24 17:23 UTC, juandbc commented on src/main/java/Wolox/training/models/Book.java
> +    public Book(String title, String author, String gender, String image, String subtitle, String publisher, String year, Integer pages, String isbn) {
Here is missing the default non args constructor that is required JPA
```suggestion

   public Book() {}

    public Book(String title, String author, String gender, String image, String subtitle, String publisher, String year, Integer pages, String isbn) {
```

2022-02-24 17:23 UTC, juandbc commented on src/main/java/Wolox/training/models/Book.java
> +    @Column(nullable = false)
The isbn should be also unique

2022-02-24 17:23 UTC, juandbc commented on src/main/java/Wolox/training/models/Book.java
> +    private long id;
When working with ORMs such as Hibernate, it is recommended to use the wrapper class for the type of the primary keys
```suggestion
    private Long id;
```

2022-02-24 17:23 UTC, juandbc commented on build.gradle
>  	implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
For unit tests, it is recommended to use an in-memory database such as H2, so the project does not depend on a database implementation.
```suggestion
	implementation group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
	testImplementation 'com.h2database:h2:1.4.200'
```

2022-02-25 13:31 UTC, juandbc approved these changes

2022-02-25 16:32 UTC, sebas97-stack approved these changes

2022-02-25 17:22 UTC, merged