Book repository was created.
wolox-training/enr-java pull request #3
Opened 2022-02-18 18:51 UTC by eliasrvt

## Summary
- BookRepository was created
## Trello Card
https://trello.com/c/bqZDOYCx

2022-02-21 14:02 UTC, sebas97-stack approved these changes

2022-02-24 17:48 UTC, juandbc requested changes

2022-02-24 17:48 UTC, juandbc commented on src/main/java/Wolox/training/repositories/BookRepository.java
> +    Optional<Book> findByAuthor(String author);
Spring has a set of interfaces per repository domain that already declare CRUD methods, for example `CrudRepository` and `JpaRepository`. With `JpaRepository` it extends from `CrudRepository` and also the paging and sorting functionality, so you don't need to declare the `findById` function.
```suggestion
public interface BookRepository extends JpaRepository<Book, Long> {
```

2022-02-24 17:51 UTC, juandbc commented on src/main/java/Wolox/training/repositories/BookRepository.java
> +    Optional<Book> findByAuthor(String author);
I checked that this change was made in the PR #4

2022-02-24 17:51 UTC, juandbc approved these changes

2022-02-25 16:02 UTC, merged