Feature/swagger
wolox-training/enr-java pull request #8
Opened 2022-02-23 19:45 UTC by eliasrvt

## Summary
- Swagger was added.
- Documentation for book controller were added.

## Trello Card
https://trello.com/c/XzcxMqQ7

2022-02-24 13:59 UTC, sebas97-stack approved these changes

2022-02-24 20:06 UTC, juandbc requested changes

2022-02-24 20:06 UTC, juandbc commented on src/main/java/Wolox/training/models/Book.java
> +    @ApiModelProperty("Represents the book title.")
You can also use the `ApiModelProperty` attribute `required` to indicate whether a field it is required or not. In this case, only the field **gender** it is not required
```suggestion
    @ApiModelProperty(value = "Represents the book title.", required = true)
```

2022-02-24 20:06 UTC, juandbc commented on src/main/java/Wolox/training/config/SwaggerConfig.java
> +                .build().apiInfo(apiEndPointsInfo());
```suggestion
                .apis(RequestHandlerSelectors.any())
                .paths(PathSelectors.any())
                .apiInfo(apiEndPointsInfo())
                .build();
```

2022-02-24 20:08 UTC, juandbc commented
There is a MacOS file `DS_Store`, you need to remove them and add it to .gitignore file

2022-02-25 13:52 UTC, juandbc approved these changes

2022-02-25 16:05 UTC, merged